### ISSUE TITLE
Problem with parameters (On private database - POST)

### ISSUE THREAD

**Issue by Servuc** [ovh/php-ovh#63] opened 2017-06-26 08:36 UTC
Hello,

I've try to create a new private database, but there is an internal problem. API returns `Received not described parameters: (serviceName)`. But I set the parameter :

```
$servers = $conn->post('/hosting/privateDatabase/lsXXXXXX-001/database', array(
	'serviceName' => "clients",
	'databaseName' => "clients"
));
print_r($servers);
```

So I also try :

```
$servers = $conn->post('/hosting/privateDatabase/lsXXXXXX-001/database', (object)array(
	'serviceName' => "clients",
	'databaseName' => "clients"
));
print_r($servers);
```

And I get : 

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.ovh.com/1.0/hosting/privateDatabase/lsXXXXXX-001/database` resulted in a `400 InvalidArgument` response:
{"message":"Received not described parameters: (serviceName) while calling creation handler"}
 in /tmp/api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /tmp/api/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /tmp/api/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /tmp/api/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /tmp/api/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /tmp/api/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promi in /tmp/api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

Thanks ;)

**Comment by VincentCasse** [comment] 2017-06-26 09:34
Hi @Servuc,

This is not a issue caused by the php-ovh. So i will close this issue.

But, I can help you! serviceName is a field that you already send because it is included into the url. Here the serviceName is 'lsXXXXXX-001'. So you don't need to push it into the array of values.

Vincent

**Closed by VincentCasse** 2017-06-26 09:34 UTC
