### ISSUE TITLE
guzzlehttp/psr7:3.0 -> Attempted to call function "build_query" from namespace "GuzzleHttp\Psr7".

### ISSUE THREAD

**Issue by rdemendoza** [ovh/php-ovh#110] opened 2021-07-11 06:33 UTC
In Api.php line 266:
Attempted to call function "build_query" from namespace "GuzzleHttp\Psr7".

Namespace: GuzzleHttp\Psr7
Deprecated: build_query will be removed in guzzlehttp/psr7:2.0. Use Query::build instead.

PS: Works with :  $query = \GuzzleHttp\Psr7\Query::build($query);

**Comment by malohtie** [comment] 2021-08-11 23:19
currently facing the same problem !

**Comment by laurentj** [comment] 2021-09-09 13:31
Many unit tests of the library are broken because of this issue

**Comment by malohtie** [comment] 2021-09-11 16:19
@laurentj i opened a PR that fix the issue but no response from them

**Comment by laurentj** [comment] 2021-09-13 07:16
@malohtie yes I saw it. There are two PR for this issue :-) . However, it seems they doesn't follow all rules indicated into [CONTRIBUTING.rst](https://github.com/ovh/php-ovh/blob/master/CONTRIBUTING.rst): you forgot to sign your commit message. I think you should add something like that into the message:

```
Signed-off-by: Random J Developer <random@developer.org>
```

**Comment by malohtie** [comment] 2021-09-30 10:01
@laurentj yeh it not signed, i guess the repo is not active anymore, no response from ovh team

**Comment by clementmoulin** [comment] 2022-02-09 12:07
This issue and the related PR must be resolved, because it's now a fatal error:
`Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()`

**Comment by soflane** [comment] 2022-06-29 10:12
Having the same problem on the /domain command

**Comment by strstr1** [comment] 2022-06-29 14:15
@soflane 

To fix the issue, do following:

1. Open /src/Api.php
2. On line 266 replace:

`$query = \GuzzleHttp\Psr7\build_query($query);`

with:

`$query = \GuzzleHttp\Psr7\Query::build($query);`

**Comment by rbeuque74** [comment] 2022-08-01 17:11
Hello everybody,
Sorry for the delay.
Pull-request #116 that fixed the issue is now merged.
I will release a new version soon.

Sorry again
Romain

**Closed by rbeuque74** 2022-08-01 17:11 UTC
