### ISSUE TITLE
how to get OVH Application Key

### ISSUE THREAD

**Issue by hosamalzagh** [ovh/php-ovh#126] opened 2023-05-08 07:07 UTC
where i can see OVH Application Key

**Comment by deathiop** [comment] 2023-05-29 14:46
As the problem is not related to the php-ovh wrapper, I will close this issue, and let you send your issue to our customer mailing-list, [api@ml.ovh.net](mailto:api@ml.ovh.net). You can subscribe by sending an email to [api-subscribe@ml.ovh.net](mailto:api-subscribe@ml.ovh.net).

**Closed by deathiop** 2023-05-29 14:46 UTC
