### ISSUE TITLE
Server::InternalServerError

### ISSUE THREAD

**Issue by FloriaanLry** [ovh/php-ovh#123] opened 2022-08-04 19:43 UTC
Hello,

I encounter a **Server::InternalServerError** error from the [OVH console](https://api.ovh.com/console/) and from my PHP script.

**API called:** POST /domain/{serviceName}/nameServers/update

**Here is the information obtained:**
Internal Server Error (500){ "class": "Server::InternalServerError", "message": "Internal server error" } _199ms_

**Screenshot from Console :** [Here](https://infinity.florianleroy.fr/c4eb0062-aac9-44d3-b967-16190bf0c36b.png)
**PHP error :** 
`Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: POST https://api.ovh.com/1.0/domain/website.com/nameServers/update resulted in a 500 Internal Server Error response: {"class":"Server::InternalServerError","message":"Internal server error"} in /var/www/vhosts/my-domain.com/httpdocs/ovh/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/vhosts/my-domain.com/httpdocs/ovh/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create() #1 /var/www/vhosts/my-domain.com/httpdocs/ovh/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 /var/www/vhosts/my-domain.com/httpdocs/ovh/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler() #3 /var/www/vhosts/my-domain.com/httpdocs/ovh/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/vhosts/my-domain.com/httpdocs/ovh/guzzlehttp/promises/src/Promise. in /var/www/vhosts/my-domain.com/httpdocs/ovh/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113`

The error also comes from the API, so the problem does not seem to come from me, but I give you my exact error code sent by PHP for referencing reasons;

Thank you to the OVH team for quickly correcting this problem or for enlightening me.
_Best regards,_

**Comment by rbeuque74** [comment] 2022-08-08 15:34
Hello @FloriaanLry,
Thanks for your report.

As you mentioned, the error comes from the API, and not from your code or the `php-ovh` wrapper.
As the issue is server-side, I will redirect you to our community mailing-list for the API: you can subscribe by sending an email to `api-subscribe@ml.ovh.net`, then send your report to `api@ml.ovh.net` once subscribed.

People from the Domain team are subscribed to this mailing-list and will reply to you regarding this issue.
I already warned them about the issue to start the fix ASAP.

Thanks for your report, I will close this issue as it will be handled on api@ml
Romain

**Closed by rbeuque74** 2022-08-08 15:34 UTC
